Updates

diff --git a/install b/install
--- a/install
+++ b/install
@@ -68,6 +68,7 @@ if [[ $DO_UPDATE -gt 0 ]]; then
     fi
     if [[ $DO_UPDATE -le 2 ]]; then
         subtitle "Installing dependencies"
+        [[ -z $(yay --version) ]] && echo "Missing yay (AUR helper)" >&2 && exit 1
         VVV=`[[ -n $VERBOSE ]] && echo "--verbose" || echo "-q"`
         yay $VERBOSE -S --needed --noconfirm $VVV - < $DATADIR/dependencies.txt
         cargo install $(cat $DATADIR/rust-dependencies.txt)
