Check cached versions

diff --git a/install b/install
--- a/install
+++ b/install
@@ -16,7 +16,8 @@ CLI=(
     -f "user-files;Copy user files to home directory;;u"
     -f "binaries;Install binaries;;b"
     -f "config;Apply configurations;;c"
-    -f "dependencies;Install dependencies (implies -b);;d"
+    -f "dependencies;Install dependencies (implies -b -w);;d"
+    -f "web-dependencies;Install web dependencies (implies -b);;w"
     -f "system;Update system packages;;s"
     -f "all;All normal targets (no remote updates);;a"
     -f "all-really;All targets (including remote updates);;A"
@@ -24,7 +25,6 @@ CLI=(
 CLI=$($DATADIR/spongecrab --name "$APP_NAME" --about "$ABOUT" "${CLI[@]}" -- "$@") || exit 1
 eval "$CLI" || exit 1
 # Post process args
-[[ -z $args_dependencies ]] || args_binaries=1
 if [[ -n $args_all_really ]]; then
     args_system=1
     args_dependencies=1
@@ -34,6 +34,12 @@ if [[ -n $args_all ]]; then
     args_config=1
     args_binaries=1
     args_user_files=1
+fi
+if [[ -n $args_dependencies ]]; then
+    args_web_dependencies=1
+fi
+if [[ -z $args_dependencies ]] && [[ -z $args_web_dependencies ]]; then
+    args_binaries=1
 fi
 HOSTNAME=$args_hostname
 NOTIFY_RELOGIN=$args_config
@@ -78,15 +84,39 @@ update_dependencies() {
     paru -S --quiet --needed --noconfirm $(cat $DATADIR/deps-aur.txt)
     # Cargo install
     cargo install $(cat $DATADIR/deps-rust.txt)
-    # Web
-    recreatedir $CACHEDIR/bin
+}
+
+update_dependencies_web() {
+    progress "Installing web dependencies"
+    local dependencies_file=$DATADIR/deps-web.txt
+    local cache_dir=$CACHEDIR/bin
     while read dep; do
         [[ -n $dep ]] || continue
-        name=$(echo $dep | cut -d' ' -f1)
-        url=$(echo $dep | cut -d' ' -f2-)
-        wget --quiet --https-only --show-progress --output-document $CACHEDIR/bin/$name "$url"
-        chmod +x $CACHEDIR/bin/$name
-    done < $DATADIR/deps-web.txt
+        local name=$(echo $dep | cut -d' ' -f1)
+        local required_version=$(echo $dep | cut -d' ' -f2)
+        local url=$(echo $dep | cut -d' ' -f3-)
+        # Check if valid version exists in cache
+        local cached_bin="$cache_dir/$name"
+        if [[ -x $cached_bin ]]; then
+            eval "cached_version=\"$($cached_bin --version 2>/dev/null || echo $name 0.1.0)\""
+            echo -n "cached version: '$cached_version'"
+            if [[ $cached_version = *${required_version}* ]]; then
+                echo " - up to date [v$required_version]"
+                continue
+            else
+                echo " - version mismatch [$cached_version != *$required_version*]"
+            fi
+        fi
+        echo "Installing $name v$required_version"
+        install_web_dependency $url $cached_bin
+    done < $dependencies_file
+}
+
+install_web_dependency() {
+    local url="$1"
+    local file="$2"
+    wget --no-verbose --https-only --show-progress --output-document $file $url
+    chmod +x $file
 }
 
 install_binaries() {
@@ -151,6 +181,7 @@ progress "Installing iuk"
 setup_installation_dirs
 [[ -z $args_system ]] || update_system
 [[ -z $args_dependencies ]] || update_dependencies
+[[ -z $args_web_dependencies ]] || update_dependencies_web
 [[ -z $args_binaries ]] || install_binaries
 [[ -z $args_config ]] || configure_group_iuk
 [[ -z $args_config ]] || configure_kmonad
